photohire/urls.py
from django.contrib import admin 
from django.urls import path,include 
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# Import all the views from 'views.py'
from photohireapp.views import *

app_name='photohireapp'

urlpatterns = [
    path('', home, name = 'home'),
    path('admin/', admin.site.urls),        # Django default URL
    path('explore/', explore, name='explore'),
    path('sign-in/', signin, name='signin'),
    path('sign-up/', signup, name='signup'),
    path('about/', about, name='about'),
    path('search/', search, name='search'),

    # Takes to a user profile with specific ID
    path('user_profile/<int:user_id>', user_profile, name="user_profile"),
	path('logout_view/', logout_view, name='logout_view'),

    # Likes an image with specific ID
    path('like/<int:img_id>', like_image, name='like_image'),
    path('upload_images/<int:user_id>', upload_images, name = 'upload_images'),

    # Deletes a photo with id=image_id
    path('delete_image/<int:image_id>', delete_image, name = 'delete_image'),
    path('edit_profile/<int:user_id>', edit_profile, name = 'edit_profile'),

    # Hire a photographer with id=pg_id
    path('hire/<int:pg_id>', hire, name="hire"),


    ############## Start : Password reset URLs ##############

    # Forget Password - Renders "password_reset_form.html"
    # "auth_views.PasswordResetView.as_view" view below is a library and it's executed by django
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
             template_name='registrations/password_reset_form.html',
             subject_template_name='registrations/password_reset_subject.txt',
             email_template_name='registrations/password_reset_email.html'
         ),
         name='password_reset'),


    # User get redirected here after entering his/her email - Renders "password_reset_form.html"
    # "auth_views.PasswordResetDoneView.as_view" view below is a library and it's executed by django
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registrations/password_reset_done.html'
         ),
         name='password_reset_done'),


    # User comes here when he/she clicks the link in the email - Renders "password_reset_confirm.html"
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registrations/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),


    # This is for information after user has changed the password
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registrations/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    ############## END : Password reset URLs ##############
]

# This is additional URL used for Static content (i.e CSS and JavaScript etc.)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# This is additional URL used for Media content (i.e images, profile pictures etc.)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photohireapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save

from django.dispatch import receiver

class Profile(models.Model):
    first_name = models.CharField(max_length=200,default='first')
    last_name = models.CharField(max_length=200,default='second')
    user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,default=1)
    bio = models.TextField(blank=True, default="")
    is_photographer = models.BooleanField(default=False)
    profile_views = models.IntegerField(default=0)
    profile_picture = models.ImageField(upload_to='images/',blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



class Tags(models.Model):
    tag = models.CharField(max_length=200)
    def __str__(self):
        return self.tag

    class Meta:
        ordering = ['tag']


class Images(models.Model):
    image = models.ImageField(upload_to='images/')
    user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    tags = models.ForeignKey(Tags, on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(default=0)
    upload_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.image)

    class Meta:
        ordering = ['upload_timestamp']


class Bookings(models.Model):
    user_id = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='customer_id')
    photographer_id = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='photographer_id')
    event = models.CharField(max_length=300)
    booking_from = models.DateField(auto_now=False)
    booking_to = models.DateField(auto_now=False)
    booking_timestamp = models.DateTimeField(auto_now=True)

class Social(models.Model):
    user_id = models.OneToOneField(Profile, on_delete=models.CASCADE, primary_key=True)
    twitter_handle = models.CharField(max_length=200, blank=True)
    instagram_id = models.CharField(max_length=200, blank=True)
    facebook_id = models.CharField(max_length=200, blank=True)
    youtube_channel = models.CharField(max_length=200, blank=True)

class Ratings(models.Model):
    rating = models.IntegerField(choices=[(i, i) for i in range(0, 6)], blank=True)
    review = models.CharField(blank=True, max_length=200)
    user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)

photohireapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect,reverse
from django.views.decorators.csrf import csrf_exempt 
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib import messages
from django.core.mail import send_mail
from .forms import *
from .models import *
import random

def logout_view(request):
    logout(request)
    return redirect('signin')

def user_profile(request):
        if request.method=='POST':
            form= editprofileform(request.POST, instance=request.user)
            if form.is_valid():
                bio=form.cleaned_data['bio']
                user=User.objects.get(id=request.user.id).id
                update=Profile.objects.filter(user=user).update(bio=bio)
            else:
                print(form.errors)
        else:
            form=editprofileform(instance=request.user)

        return render(request,'photohireapp/edit_profile.html',{'form':form})
	
def home(request):
    # Get all images by number of likes
    # Minus (-liked) if for descending order
    images = list(Images.objects.all().order_by('-likes'))

    # Get top 5 photographers based on Profile views
    photographers = list(Profile.objects.filter(is_photographer=True).order_by('-profile_views')[:5])

    # Shuffle lists
    random.shuffle(photographers)

    # Get first 3 from the shuffled list of 5 photographers
    top_photographers = photographers[0:3]

    # Return all images and only 3 photographers
    return render(request, 
        'photohireapp/index.html', 
        {'images':images, 'top_photographers':top_photographers}
    )


def explore(request):
    images = list(Images.objects.all())
    random.shuffle(images)
    # Get top 10 photographers based on their profile views
    trending_photographers = Profile.objects.filter(is_photographer=True).order_by('-profile_views')[:10]
    
    list_of_pg = []
    
    for pg in trending_photographers:
        rating_obj = Ratings.objects.filter(user_id=pg.id)
        ratings = [r.rating for r in rating_obj]

        if len(ratings):
            avg_rating = round(sum(ratings)/len(ratings),1)
        else:
            avg_rating = -1

        pg.rating = avg_rating
        list_of_pg.append(pg)

    return render(request, 
        'photohireapp/expore.html',
        {'images':images, 'list_of_pg':list_of_pg}
    )


# csrf_exempt is for all the form related views in django
@csrf_exempt
def signup(request):
    # POST request when clicked on submit
    if request.method=='POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            user =form.save()
            user.refresh_from_db()
            user.profile.first_name=form.cleaned_data.get('first_name')
            user.profile.last_name=form.cleaned_data.get('last_name')

            # Set is_photographer to True or False based on the radio button pressed
            user.profile.is_photographer = True if request.POST['is_photographer'] == "photographer" else False

            # Set email = username
            user.email = user.username
            user.save()
            raw_password = form.cleaned_data.get('password1')

            # make the user login automatically after sign-up
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            # Add success message
            messages.add_message(request, messages.INFO, "Congrats! You signed up successfully!")

            return redirect('/')
        else:
            messages.add_message(request, messages.INFO, str(form.errors))
            print(form.errors)
            return redirect('/sign-up')
    else:
        form=UserCreationForm()
        args={'form':form}
        return render(request,"photohireapp/sign-up.html",args)
    return render(request, 
        'photohireapp/sign-in.html'
    )


@csrf_exempt
def signin(request):

    # When user clicked Submit
    if request.method =='POST':

        # Get all data from request.POST
        form=LoginForm(request.POST)

        if form.is_valid():
            cd =form.cleaned_data

            # Check if user is correct
            user=authenticate(username = cd['email'] , password = cd['password'])

            # If user is there, make him login
            if user:
                login(request,user)
                return redirect('/user_profile/'+str(user.id))
            
            # Give him an error of 404
            else:
                messages.add_message(request, messages.INFO, "User does not exist!")
        
        # If the form if invalid, just print errors
        else:
            print(form.errors)
            messages.add_message(request, messages.INFO, str(form.errors))

    # When user came on login page
    else:
        form=LoginForm()
    return render(request , 'photohireapp/sign-in.html',{'form' :form})


def about(request):
    return render(request, 
        'photohireapp/about.html'
    )

def search(request):
    # Get tag searched by user
    tag=request.GET['search']

    # contains case insensitive value of the query
    tagged_images = Images.objects.filter(tags__tag__icontains=tag)

    # Get all the tags
    all_tags = list(Tags.objects.all())
    random.shuffle(all_tags)

    # Get all tags, that have atleast one image for them
    tags_with_images = []

    # Iterate for all tags
    for tag_ in all_tags:

        # If image exists for that tag
        if Images.objects.filter(tags__tag__icontains=tag_).count()>0:

            # Add that tag to the tags_with_images
            tags_with_images.append(tag_)

    return render(request,
        'photohireapp/search.html',
        {
            'tagged_images': tagged_images,
            'tag':tag,
            'all_tags': tags_with_images
        }
    )

def user_profile(request, user_id):

    # Get all data for that user
    user_data = Profile.objects.get(id=user_id)

    # Increase his views by 1
    user_data.profile_views = user_data.profile_views + 1
    user_data.save()

    ## Get social_data if it exists
    try:
        social_data = Social.objects.get(user_id=user_id)
    except Exception:
        social_data = {}
    
    ## Calculate average rating
    rating_obj = Ratings.objects.filter(user_id=user_id)
    ratings = [r.rating for r in rating_obj]

    if len(ratings) > 0:
        # Round off to only one digit to have ratings like 4.3 and not 4.333333333
        avg_rating = round(sum(ratings)/len(ratings), 1)
    else:
        avg_rating = -1
    
    bookings = Bookings.objects.filter(photographer_id=user_id)

    # Any number between 5 and 15
    n_recommended = random.randint(5,15)
    # randomly pick 'n_recommended' images from the database
    recommended_images = Images.objects.order_by('?')[:n_recommended]
    ## Reviews and ratings
    if request.method=="POST":
        rating_form = RatingsForm(request.POST)
        rating_form.save()
    else:
        rating_form = RatingsForm()

    # Photos uploaded by current photographer
    uploaded_images = Images.objects.filter(user_id=user_id)

    context = {'user_data':user_data,
        'recommended_images':recommended_images,
        'uploaded_images': uploaded_images,
        'avg_rating':avg_rating,
        'rating_form': rating_form,
        'rating_obj':rating_obj,
        'social_data': social_data,
        'bookings': bookings
        }

    return render(request, 'photohireapp/profile.html', context)


def like_image(request, img_id):
    img_data = Images.objects.get(id=img_id)
    img_data.likes = img_data.likes + 1
    img_data.save()

    # Return to the same page
    return redirect(request.META['HTTP_REFERER'])


def upload_images(request, user_id): 

	if request.method == 'POST': 
		form = ImagesForm(request.POST, request.FILES) 

		if form.is_valid(): 
			form.save()
			messages.add_message(request, messages.INFO, "Image Uploaded successfully!")
			
			# Redirect to the same page
			return redirect(request.META['HTTP_REFERER'])
		else:
			messages.add_message(request, messages.INFO, str(form.errors))
	else: 
		form = ImagesForm() 
	return render(request, 'photohireapp/upload_images.html', {'form' : form, 'user_id':user_id})


def delete_image(request, image_id):
    instance = Images.objects.get(id=image_id)
    instance.delete()
    
    # Add message
    messages.add_message(request, messages.INFO, "Image deleted successfully")

    # Redirect to the same page again
    return redirect(request.META['HTTP_REFERER'])


@csrf_exempt
def edit_profile(request, user_id):
    user_data = Profile.objects.get(id=user_id)
    try:
        social_data = Social.objects.get(user_id=user_id)
    except Exception as e:
        print(e)
        social_data = {}

    if request.method == "POST":
        pofile_form = ProfileForm(request.POST or None, request.FILES or None,  instance=user_data)

        # If social data not retrieved, get a creat form else get an update form
        if social_data == {}:
            social_form = SocialForm(request.POST)
        else:
            social_form = SocialForm(request.POST, instance=social_data)

        # If both forms valid, proceed forward
        if pofile_form.is_valid() and social_form.is_valid():
            profile_edit = pofile_form.save(commit=False)
            profile_edit.save()
            social_edit = social_form.save(commit=False)
            social_edit.save()
            return redirect('/user_profile/'+str(user_id))
        else:
            print(pofile_form.errors, social_form.errors)
    return render(request, 'photohireapp/edit_profile.html', {'user_data':user_data, 'social_data':social_data})


def send_hiring_emails(request_values):
    print(request_values)

    # Get necessary values first
    event = request_values['event']
    booking_from = request_values['booking_from']
    booking_to = request_values['booking_to']

photohireapp/templates/photohireapp/about.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'photohireapp/css/about.css' %}">
{% endblock %}

{% block title %}About{% endblock %}

{% block content %}
  <head>
      <link rel="stylesheet" href="AboutUs.css">
  </head>
  <body>
      <div class = "heading">
          <h1>About Us</h1>
      </div>
      <div class="container">
          <section id = "main">
              <h1>Welcome</h1>
              <p>
                  <b>Find Your lensman</b> is a website which provides photographer to a user according to their selected categories,
                  A user can find his 'Lesnman' easily by just searching the name of the photographer.
                  <h5>Some Features Of FLY Are :</h5>
                  <ul>
                      <li>Fast</li>
                      <li>Better User Interface</li>
                      <li>Better Experience</li>
                  </ul>
              </p>
              <p>You can mail your problems at <font style="color: blue;">https://www.findyourlensman.com</font></p>
          </section>
  
          <aside id = "side-bar">
              <h2>Why use FYL?</h2>
              <p style="font-family: arial;">
                  To get a proper photographer we have to visit each and every photographers place which tends to very hectic.
                  So to save that energy and save that time Find Your Lensman plays a vital role in every users life, FLY provides photographers to its users
                  by simpply just taking the photographers name as a user input.
              </p>
          </aside>
      </div>
      <footer id = "main-footer">
          <p>Find Your Lensman Since 2020</p>
      </footer>
  </body>
{% endblock %}

photohireapp/templates/photohireapp/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit-Profile{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'photohireapp/css/edit_profile.css' %}"> 
{% endblock %}



{% block content %}
<div class="edit-your-profile">
    <div class="form-model">
        <h1>Edit Your Profile</h1><br>
        <form method="POST" action="#" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Profile Model -->
            <div class="choose-filee">
                Change profile picture: &nbsp;&nbsp;&nbsp;
                <input type="file" accept="image/*" name="profile_picture" value={{ user_data.profile_picture }}>
            </div>
            <div class="names">
                <div class="name">
                    <label for="">First Name</label>
                    <input type="text"  name="first_name" value="{{ user_data.first_name }}">
                </div>
                <div class="last">
                    <label for="">Last Name</label>
                    <input type="text"  name="last_name" value="{{ user_data.last_name }}">
                </div>
            </div>
            {% comment %} <div class="bio">
                <label for="">Short Bio</label>
                <textarea name="bio" id="" cols="20" rows="10" value="{{ user_data.bio }}"></textarea>
            </div> {% endcomment %}

            <!-- Social Model -->
            <div class="hidden-id-filed" style="display:none;">
                <label for="id_user_id">User ID</label>
                <input name="user_id" type="text" value="{{ user_data.id }}">
            </div> <br>
            <div class="insta-username">
                <label for="Instagram Username">Instagram Account link</label>
                <input name="instagram_id" type="url" value="{{ social_data.instagram_id }}">
            </div>
            <div class="twitter-username">
                <label for="">Twitter Handle Link</label>
                <input name="twitter_handle" type="url" value="{{ social_data.twitter_handle }}">
            </div>
            <div class="twitter-username">
                <label for="">Facebook Profile Link</label>
                <input name="facebook_id" type="url" value="{{ social_data.facebook_id }}">
            </div>
            <div class="twitter-username">
                <label for="">Youtube Channel Link</label>
                <input name="youtube_channel" type="url" value="{{ social_data.youtube_channel }}">
            </div>

            <div class="update-cancel">
                <a href="{% url 'user_profile' user_id=user_data.id %}">
                    <button id="cancelBtn" class="update">Cancel</button> &nbsp;&nbsp;&nbsp;
                </a>
                <button class="update" type="Submit">Update Profile</button>
            </div>

        </form>
    </div>
</div>
{% endblock %}

photohireapp/templates/photohireapp/expore.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'photohireapp/css/index.css' %}">
  <link rel="stylesheet" href="{% static 'photohireapp/css/explore.css' %}">
  <style>
  section.features-section {
      margin-top: -60px;
  }
  .toggleDiv{
    text-align: center;
    color: gray;
    margin-top: 10px;
  }
  
  </style>
{% endblock %}

{% block title %}Explore{% endblock %}

{% block content %}
  <div class="toggleDiv">
    <h2>
      <a href="#"><span id="photosBtn">Photos</span></a>  |   <a id="lbBtn" href="#">Leaderboard</a>
    </h2>
  </div>
  <div id="photosSection" class="container">
    <main>
      <div class="home-gallery">
          <ul class="trending flex jc-around ai-center">
              {% for photographer in top_photographers %}
              <li>
                  <a href="#">
                      <img class="hoverimg" src="http://127.0.0.1:8000/media/{{ photographer.profile_picture }}" alt="">
                      <span>{{ photographer.first_name }} {{ photographer.last_name }}</span>
                  </a>
              </li>
              {% endfor %}
          </ul>
      </div>
      <section class="features-section">
          <ul class="featured-img">
              {% for image in images %}
              <li class="imageLi">
                  <img class="list_image" src="http://127.0.0.1:8000/media/{{ image }}" alt="">
                  <a href="/user_profile/{{ image.user_id.id }}">
                    <div class="middle">
                      <div class="visit_photographer">Visit Photographer</div>
                    </div>
                  </a>
              </li>
              {% endfor %}
          </ul>
      </section>
    </main>
  </div>
  <div id="lbSection" style='display:none'>
      <div>
        <head>
            <title>Leaderboard </title>
            <link rel="stylesheet" media="screen" href="assets/css/leaderboard.css">
        </head>
        <div class="leaderboard">
            <ul class="board">
                {% for pg in list_of_pg %}
                    <li>
                        <a href="/user_profile/{{ pg.id }}">
                            {% if pg.profile_picture|length > 1 %}
                              <img src="http://127.0.0.1:8000/media/{{ pg.profile_picture }}" alt="">
                            {% else %}
                              <img src="{% static 'photohireapp/images/user-placeholder.jpg' %}" alt="">
                            {% endif %}
                        </a>
                        <div>
                            <p class="profile-name">{{ pg.first_name }} {{ pg.last_name  }}
                            {% if pg.rating != -1 %}
                              -<i> {{ pg.rating }}/5</i>
                            {% else %}
                              -<i> NA</i>
                            {% endif %}
                            </p>
                            <p class="visit"><span class="visit-count"></span>Profile Visits - {{ pg.profile_views  }}</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
  </div>
  <script> 
    // Get the elements
    var photosBtn = document.getElementById("photosBtn");
    var lbBtn = document.getElementById("lbBtn");
    var photosSection = document.getElementById("photosSection");
    var lbSection = document.getElementById("lbSection");

    // Style photosBtn initially by default
    photosBtn.style.textDecoration = "underline";
    photosBtn.style.color = "blue";
    photosBtn.style.fontStyle = "italic";

    // When clicked on photosBtn change style and hide lbSection
    photosBtn.onclick = function() {
      console.log("Photos Button");
      photosBtn.style.color = "blue";
      lbBtn.style.color = "gray";
      photosBtn.style.textDecoration = "underline";
      photosBtn.style.fontStyle = "italic";
      lbBtn.style.fontStyle = "";
      lbBtn.style.textDecoration = "";
      photosSection.style.display = "block";
      lbSection.style.display = "none";
    }

    // When clicked on lbBtn change style and hide photosSection
    lbBtn.onclick = function() {
      console.log("LB Button");
      photosBtn.style.color = "gray";
      lbBtn.style.color = "blue";
      photosBtn.style.textDecoration = "";
      lbBtn.style.textDecoration = "underline";
      photosBtn.style.fontStyle = "";
      lbBtn.style.fontStyle = "italic";
      photosSection.style.display = "none";
      lbSection.style.display = "block"
    }

  </script>
{% endblock %}

photohireapp/templates/photohireapp/hire.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'photohireapp/css/hire.css' %}">
{% endblock %}

{% block title %}Hire{% endblock %}

{% block content %}

<div class="mainDiv">
    <br><br>
    <h1>Hire Photographer</h1>
    <br><hr><br>
    <form class="hireForm" method="POST" action="#">
        {% csrf_token %}
        <div class="form-box">

            <!-- Hide field values that are already known -->
            <div class="form-input-div"style="display: none;">
                <label for="user_id">User ID</label>
                <input name='user_id' value='{{ user.id  }}'>
            </div>

            <!-- Hide field values that are already known -->
            <div class="form-input-div"style="display: none;">
                <label for="photographer_id">Photographer ID</label>
                <input name='photographer_id' value='{{ pg_id }}'>
            </div>

            <div class="form-input-div">
                <label class="textLable" for="id_event">Event &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</label>
                &nbsp;&nbsp;&nbsp;&nbsp;<input class="inputText" type="text" name="event" maxlength="300" required="" id="id_event" placeholder="Marriage, Reception, Art ..">
            </div>
            <br>
            <div class="form-input-div">
                <label class="textLable" for="id_booking_from">Booking from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</label>
                &nbsp;&nbsp;&nbsp;&nbsp;<input type="date" name="booking_from" required="" id="id_booking_from">
            </div>
            <br>
            <div class="form-input-div">
                <label class="textLable" for="id_booking_to">Booking to&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</label>
                &nbsp;&nbsp;&nbsp;&nbsp;<input type="date" name="booking_to" required="" id="id_booking_to">
            </div>
            <br>
        </div>
        <br>
        <button class="submit-btn" type="Submit">Hire</button>
    </form>
</div>

<script>
    // Do not let user select past dates
    document.getElementById('id_booking_from').min = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
    document.getElementById('id_booking_to').min = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
</script>
{% endblock %}

photohireapp/templates/photohireapp/search.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'photohireapp/css/search.css' %}">
{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
  <div class="container">
    <main>
        <section class="features-section">
          {% if tagged_images|length > 0 %}
            <div class="searchDiv">
              <h1>
                  Showing results for <i>"{{ tag }}"</i>, try other tags like:
              </h1>
                  {% for tag_ in all_tags %}
                    <a href="{% url 'search' %}?search={{ tag_ }}" class="tagClass" href="">{{ tag_ }}</a>
                  {% endfor %}
            </div>
            <ul class="featured-img">
                {% for image in tagged_images %}
                <li class="imageLi">
                    <a href="#">
                        <img src="http://127.0.0.1:8000/media/{{ image }}" alt="">
                    </a>
                </li>
                {% endfor %}
            </ul>
          {% else %}
            <div class="searchDiv">
              <h1>
                  No results found for  <i>"{{ tag }}"</i>, try one of the following tags
              </h1>
                {% for tag_ in all_tags %}
                  <a href="{% url 'search' %}?search={{ tag_ }}" class="tagClass" href="">{{ tag_ }}</a>
                {% endfor %}
            </div>
          {% endif %}
        </section>
    </main>
  </div>
  <script>
    document.getElementById("searchField").value = "{{ tag }}";
  </script>
{% endblock %}

photohireapp/templates/photohireapp/signin.html
<div class="sign-up-contaner">
    <head>
        <title>Sign In Page </title>
        <link rel="stylesheet" media="screen" href="assets/css/style.css">
    </head>
    <style>
        .sign-up-contaner .sign-up{
            background:#000 url('./signbg.jpg') no-repeat center;
            height: 100vh;
            background-size: cover;
        }
    </style>
    <div class="sign-up">
        <div class="form-box">
            <form action="">
                <div class="email input-box">
                    <label for="">Email</label>
                    <input class="inp" type="email">
                </div>
                <div class="pass input-box">
                    <label for="">Password</label>
                    <input class="inp" type="password">
                </div>
                <div class="pass input-box">
                    <input class="submit-btn" type="submit" value="Sign In">
                </div>
            </form>
        </div>
    </div>
</div>

photohireapp/templates/photohireapp/upload_images.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'photohireapp/css/upload_images.css' %}">
{% endblock %}

{% block content%}

<!-- Actual form is here -->
<div class="mainDiv">
    <br><br><br><br>
    <h1>Upload photos</h1><br>
    <hr><br><br>
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form.visible_fields %}

            <!-- Handle user_id manually and set it's value from backend -->
            {% if field.name == "user_id" %}
                <input type="hidden" id="id_user_id" name="user_id" value="{{ user_id }}">
            {% else %}
                <span class="lablesText">{{ field.label_tag }} {{ field }}</span>
                <span class="errorsText"><br>{{ field.errors }} </span><br>
            {% endif %}

        {% endfor %}<br>
        <button type="submit" class="submit-btn"><i class="icon-lock4"></i> Upload</button>
    </form>
  </div>

{% endblock  %}